stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the game server code..."
    - cd server
    - echo "Building game server..."
    - docker build . -f Dockerfile.gameserver -t poker-gameserver
    - echo "Finished building game server..."
    - echo "Building site server..."
    - docker build . -f Dockerfile.siteserver -t poker-siteserver
    - echo "Finished building site server..."
    - cd ..
    - echo "Building ui..."
    - cd ui
    - docker build . -f Dockerfile.ui -t poker-ui
    - echo "Finished building ui..."
    - cd ..
    - echo "Compile complete."


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deleting old application deployment..."
    - kubectl delete -f k8s-poker/
    - echo "Deploying application..."
    - kubectl create -f k8s-poker/
    - echo "Application successfully deployed."
    - echo "Port forwarding to Mongo..."
    - kubectl port-forward service/db 27017:27017 & 
    - echo "Successfully port forwarded to Mongo..."

e2e-test-job:   # This job runs in the test stage.
  stage: test 
  rules:
    # The following prevents the pipeline from running except when run
    # manually via the GitLab web interface.
    - when: manual
  script:
    - echo "Running E2E tests..."
    - cd ui
    - docker run -t --rm --ipc=host mcr.microsoft.com/playwright:v1.28.0-focal /bin/bash -c 'npx playwright test --project=chromium'
    - echo "Finished running E2E tests..."