stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the game server code..."
    - cd server
    - echo "Building game server..."
    - docker build . -f Dockerfile.gameserver -t poker-gameserver
    - echo "Finished building game server..."
    - echo "Building site server..."
    - docker build . -f Dockerfile.siteserver -t poker-siteserver
    - echo "Finished building site server..."
    - cd ..
    - echo "Building ui..."
    - cd ui
    - docker build . -f Dockerfile.ui -t poker-ui
    - echo "Finished building ui..."
    - cd ..
    - echo "Compile complete."


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
