# vite build
FROM library/node:18-alpine as node
WORKDIR /home/node/app
COPY ui/*.js* ./
RUN npm i
COPY ui/*.ts ./
COPY ui/index.html ./
COPY ui/src ./src
RUN ls -al && npm run build

# nginx
FROM library/nginx:alpine
COPY --from=node /home/node/app/dist /usr/share/nginx/html
COPY ui/nginx.conf /etc/nginx/nginx.conf 