apiVersion: v1
kind: Service
metadata:
  labels:
    app: gameserver
  name: gameserver
spec:
  type: NodePort
  ports:
  - name: "gameserver-service"
    port: 5001
    targetPort: 8101
    nodePort: 31003
  selector:
    app: gameserver
